### PR TITLE
ENH enable more graphs

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds more graphs to the status page.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Can you provide a screenshot?

**Comment by beckermr** [comment]
Yup. Still working on this one. I removed the repo listing.

**Comment by beckermr** [comment]
Screen Shot 2020-01-29 at 12 46 25 PM

**Comment by CJ-Wright** [comment]
@beckermr is ready to go in? It looks great!

**Comment by beckermr** [comment]
yup! :shipit:

**Comment by CJ-Wright** [comment]
Also side note, is this all getting tracked in the DB? Does that mean that we could then produce this graph for all time?

**Pull request merged**
