### PR TITLE
ENH add github actions usage to status page

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
OK ready @scopatz

**Comment by scopatz** [comment]
Can you also make the same change to the `template.html` file too, so it isn't overwritten when index.html is regenerated? Thanks!

**Comment by beckermr** [comment]
Ack! I did not realize that was being rendered! Yup!

**Comment by beckermr** [comment]
done @scopatz ! back to you!

**Comment by scopatz** [comment]
Cool thanks!

**Pull request merged**
