### PR TITLE
Migrator Status

### PR DESCRIPTION
**Pull request by scopatz**
Adds migrator status to the page.

### CODE REVIEW

**Comment by scopatz** [comment]
CC @mariusvniekerk

**Comment by jakirkham** [comment]
Neat! Would it be possible to have links to the PRs? Might help us triage them faster. :)

**Comment by jakirkham** [comment]
Sorry for the rapid follow-up comment. I think we need to move this to `template.html`. The `index.html` file is autogenerated. So this might get wiped out if we leave it in `index.html`.

**Comment by CJ-Wright** [comment]
@mariusvniekerk had a nice link for this but I use https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Aregro-cf-autotick-bot+archived%3Afalse+Rebuild+for+Python

**Comment by scopatz** [comment]
@jakirkham 

> Would it be possible to have links to the PRs? Might help us triage them faster. :)

Yes, that would be great, but that would require an update to cf-scripts to provide the PR links.  we should probably open this as a feature issue there.

> Sorry for the rapid follow-up comment. I think we need to move this to template.html. The index.html file is autogenerated. So this might get wiped out if we leave it in index.html.

It actually is in `template.html` already, The reason I added it to index.html was so that I could test it locally.  Ideally it would have been nice to be able to rerender, but I don't have access / know where to find the token :wink:

**Comment by CJ-Wright** [comment]
I think we may have access to the pr urls in the pred_json.

**Comment by mariusvniekerk** [comment]
Do you propose changing the json structure to have links?

**Comment by scopatz** [comment]
> Do you propose changing the json structure to have links?

Yes, perhaps.  I think that is the idea.  But I don't think we should get hung up on that here now.  This is a first cut, minimally viable solution. We can add nice new features as we go :)

**Comment by jakirkham** [comment]
Sure, if it's more complicated, it's not necessarily a priority. Just a suggestion is all. 😉

**Comment by CJ-Wright** [comment]
Thank you very much @scopatz

**Pull request merged**
